service: serverless-ts

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

custom:
  serverless-offline:
    httpPort: 3000

functions:
  add-book:
    handler: src/handler.createBook
    events:
      - http:
          path: books
          method: post
          cors: true
  get-books:
    handler: src/handler.getBooks
    events:
      - http:
          path: books
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
