service: serverless-ts

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

custom:
  serverless-offline:
    httpPort: 3000

functions:
  add-book:
    handler: src/handlers/book.createBook
    events:
      - http:
          path: books
          method: post
          cors: true
  get-books:
    handler: src/handlers/book.getBooks
    events:
      - http:
          path: books
          method: get
          cors: true
  get-book:
    handler: src/handlers/book.getBook
    events:
      - http:
          path: books/{id}
          method: get
          cors: true
  update-book:
    handler: src/handlers/book.updateBook
    events:
      - http:
          path: books/{id}
          method: put
          cors: true
  delete-book:
    handler: src/handlers/book.deleteBook
    events:
      - http:
          path: books/{id}
          method: delete
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
